### Data Preparation ensures:

- Data is relevant

- No missing values

- Categorical variables are encoded

- Features are normalized/standardized

- Outliers handled

- Data is clean & ML-ready

**80% of ML project time is spent on Data Preparation**

#### Pandas is a Data Analysis library in Python 
Pandas is a Python library used for:

- Data loading
- Data cleaning
- Data manipulation
- Data analysis
- Data preparation for Machine Learning

**It works mainly with Series (1D data) and DataFrame (2D tabular data)**

#### Most Important Pandas Functions (Quick Reference)

Numbers : 2,3.4, -9, 99999.00 
int, float,complex 
2,3.4,3+9j

"AASHI" , "A" - STR

Lists=[1,2,3]
Tuple=(1,2,3)
dic={1:"A", 2:"B"] 

sets={1,2,3,4,5}

In [4]:
a="study"
a[0]
#a.append("Is important")
a1=["study"]
a1.append("is important")

In [5]:
a1

['study', 'is important']

In [12]:
import pandas as pd
s=[1,2,3,4]
t=(1,2,3)
d={"A":"a", 2:"b", 3: "c",4:"d"}
i=("one","two", "three", "four")
s1=pd.Series(s,index=i)

In [8]:
s

[1, 2, 3, 4]

In [10]:
s1

one      1
two      2
three    3
four     4
dtype: int64

In [13]:
s2=pd.Series(d)
s2

A    a
2    b
3    c
4    d
dtype: object

In [15]:
emp =[["101","Ashi"],["102","Sid"]]
e = pd.DataFrame(emp)
e

     0     1
0  101  Ashi
1  102   Sid

In [17]:
x=list(range(12,22,2))
x

[12, 14, 16, 18, 20]

In [18]:
## Step 1: Create a Sample DataFrame (15 rows × 6 columns)
import pandas as pd
import numpy as np

# Create sample DataFrame
data = {
    'EmployeeID': range(1, 16),
    'YearsExperience': [1, 2, 3, 5, np.nan, 7, 8, 2, 4, 9, 10, 6, np.nan, 3, 4],
    'EducationLevel': ['Bachelors', 'Masters', 'Bachelors', 'Masters', 'PhD',
                       np.nan, 'Bachelors', 'Diploma', 'Masters', 'PhD',
                       'Diploma', 'Masters', 'PhD', np.nan, 'Bachelors'],
    'SkillsScore': [78, 85, np.nan, 92, 88, 70, np.nan, 80, 75, 95, 65, np.nan, 90, 82, 76],
    'Department': ['IT', 'HR', 'Finance', 'Finance', 'IT', 'HR', np.nan,
                   'IT', 'Finance', 'HR', 'Finance', 'IT', 'HR', 'HR', np.nan],
    'Hired': [1, 0, 1, 1, np.nan, 0, 1, 0, 1, 1, 0, 1, np.nan, 0, 1]
}

df = pd.DataFrame(data)

df

    EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
0            1              1.0      Bachelors         78.0         IT    1.0
1            2              2.0        Masters         85.0         HR    0.0
2            3              3.0      Bachelors          NaN    Finance    1.0
3            4              5.0        Masters         92.0    Finance    1.0
4            5              NaN            PhD         88.0         IT    NaN
5            6              7.0            NaN         70.0         HR    0.0
6            7              8.0      Bachelors          NaN        NaN    1.0
7            8              2.0        Diploma         80.0         IT    0.0
8            9              4.0        Masters         75.0    Finance    1.0
9           10              9.0            PhD         95.0         HR    1.0
10          11             10.0        Diploma         65.0    Finance    0.0
11          12              6.0        Masters          NaN         IT    1.0
12          13              NaN            PhD         90.0         HR    NaN
13          14              3.0            NaN         82.0         HR    0.0
14          15              4.0      Bachelors         76.0        NaN    1.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EmployeeID       15 non-null     int64
 1   YearsExperience  13 non-null     float64
 2   EducationLevel   13 non-null     object
 3   SkillsScore      12 non-null     float64
 4   Department       13 non-null     object
 5   Hired            13 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 852.0+ bytes

In [21]:
df.head(2)

   EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
0           1              1.0      Bachelors         78.0         IT    1.0
1           2              2.0        Masters         85.0         HR    0.0

In [ ]:
df.head()          # First 5 rows
df.tail()          # Last 5 rows
df.info()          # Datatypes, Non-null counts
df.describe()      # Summary statistics

### Stats Summary

In [22]:
df.describe()

       EmployeeID  YearsExperience  SkillsScore      Hired
count   15.000000        13.000000    12.000000  13.000000
mean     8.000000         4.923077    81.333333   0.615385
std      4.472136         2.871165     9.098784   0.506370
min      1.000000         1.000000    65.000000   0.000000
25%      4.500000         3.000000    75.750000   0.000000
50%      8.000000         4.000000    81.000000   1.000000
75%     11.500000         7.000000    88.500000   1.000000
max     15.000000        10.000000    95.000000   1.000000

In [23]:
df.describe(include="object")

       EducationLevel Department
count              13         13
unique              4          3
top         Bachelors         HR
freq                4          5

## Data Preparation

## Dealing with null values
- Real inputs 
- drop nulls 
- filling null values mean or median for numerical data
- mean gets affected but ouliers 
- median (numerial data)
- categorical mode

In [24]:
## null values
df.isnull().sum()              # Count missing values
#df[df['SkillsScore'].isnull()] # Show rows where SkillsScore is missing

EmployeeID         0
YearsExperience    2
EducationLevel     2
SkillsScore        3
Department         2
Hired              2
dtype: int64

In [25]:
df_filled = df.fillna({
    'YearsExperience': df['YearsExperience'].mean(),
    'SkillsScore': df['SkillsScore'].median(),
    'EducationLevel': 'Masters',
    'Department': 'Unknown',
    'Hired': df['Hired'].mode()[0]
})

#df_dropped = df.dropna()       # remove all rows with any missing value

In [ ]:
## column 
df['SkillsScore']
df[['YearsExperience', 'SkillsScore']]

In [26]:
## Filter functions
df[df['YearsExperience'] > 5]

    EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
5            6              7.0            NaN         70.0         HR    0.0
6            7              8.0      Bachelors          NaN        NaN    1.0
9           10              9.0            PhD         95.0         HR    1.0
10          11             10.0        Diploma         65.0    Finance    0.0
11          12              6.0        Masters          NaN         IT    1.0

In [27]:
df[(df['Department'] == 'IT') & (df['Hired'] == 1)]

    EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
0            1              1.0      Bachelors         78.0         IT    1.0
11          12              6.0        Masters          NaN         IT    1.0

In [ ]:
df

In [28]:
## Modify or add columns
df['ScoreCategory'] = np.where(df['SkillsScore'] > 80, 'High', 'Low')

In [29]:
df

,EmployeeID,YearsExperience,EducationLevel,SkillsScore,Department,Hired,ScoreCategory
0,1,1.0,Bachelors,78.0,IT,1.0,Low
1,2,2.0,Masters,85.0,HR,0.0,High
2,3,3.0,Bachelors,NaN,Finance,1.0,Low
3,4,5.0,Masters,92.0,Finance,1.0,High
4,5,NaN,PhD,88.0,IT,NaN,High
5,6,7.0,NaN,70.0,HR,0.0,Low
6,7,8.0,Bachelors,NaN,NaN,1.0,Low
7,8,2.0,Diploma,80.0,IT,0.0,Low
8,9,4.0,Masters,75.0,Finance,1.0,Low
9,10,9.0,PhD,95.0,HR,1.0,High
10,11,10.0,Diploma,65.0,Finance,0.0,Low
11,12,6.0,Masters,NaN,IT,1.0,Low
12,13,NaN,PhD,90.0,HR,NaN,High
13,14,3.0,NaN,82.0,HR,0.0,High
14,15,4.0,Bachelors,76.0,NaN,1.0,Low

In [30]:
## remove Columns
df.drop(columns=['ScoreCategory'], inplace=True)

In [31]:
df

    EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
0            1              1.0      Bachelors         78.0         IT    1.0
1            2              2.0        Masters         85.0         HR    0.0
2            3              3.0      Bachelors          NaN    Finance    1.0
3            4              5.0        Masters         92.0    Finance    1.0
4            5              NaN            PhD         88.0         IT    NaN
5            6              7.0            NaN         70.0         HR    0.0
6            7              8.0      Bachelors          NaN        NaN    1.0
7            8              2.0        Diploma         80.0         IT    0.0
8            9              4.0        Masters         75.0    Finance    1.0
9           10              9.0            PhD         95.0         HR    1.0
10          11             10.0        Diploma         65.0    Finance    0.0
11          12              6.0        Masters          NaN         IT    1.0
12          13              NaN            PhD         90.0         HR    NaN
13          14              3.0            NaN         82.0         HR    0.0
14          15              4.0      Bachelors         76.0        NaN    1.0

In [32]:
##Grouping & Aggregation
df.groupby('Department')['SkillsScore'].mean()
df.groupby('EducationLevel')['Hired'].sum()

EducationLevel
Bachelors    4.0
Diploma      0.0
Masters      3.0
PhD          1.0
Name: Hired, dtype: float64

In [33]:
## Sorting 
df.sort_values('YearsExperience')

    EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
0            1              1.0      Bachelors         78.0         IT    1.0
1            2              2.0        Masters         85.0         HR    0.0
7            8              2.0        Diploma         80.0         IT    0.0
2            3              3.0      Bachelors          NaN    Finance    1.0
13          14              3.0            NaN         82.0         HR    0.0
8            9              4.0        Masters         75.0    Finance    1.0
14          15              4.0      Bachelors         76.0        NaN    1.0
3            4              5.0        Masters         92.0    Finance    1.0
11          12              6.0        Masters          NaN         IT    1.0
5            6              7.0            NaN         70.0         HR    0.0
6            7              8.0      Bachelors          NaN        NaN    1.0
9           10              9.0            PhD         95.0         HR    1.0
10          11             10.0        Diploma         65.0    Finance    0.0
4            5              NaN            PhD         88.0         IT    NaN
12          13              NaN            PhD         90.0         HR    NaN

In [34]:

df.sort_values(['Department', 'SkillsScore'], ascending=[True, False])

    EmployeeID  YearsExperience EducationLevel  SkillsScore Department  Hired
3            4              5.0        Masters         92.0    Finance    1.0
8            9              4.0        Masters         75.0    Finance    1.0
10          11             10.0        Diploma         65.0    Finance    0.0
2            3              3.0      Bachelors          NaN    Finance    1.0
9           10              9.0            PhD         95.0         HR    1.0
12          13              NaN            PhD         90.0         HR    NaN
1            2              2.0        Masters         85.0         HR    0.0
13          14              3.0            NaN         82.0         HR    0.0
5            6              7.0            NaN         70.0         HR    0.0
4            5              NaN            PhD         88.0         IT    NaN
7            8              2.0        Diploma         80.0         IT    0.0
0            1              1.0      Bachelors         78.0         IT    1.0
11          12              6.0        Masters          NaN         IT    1.0
14          15              4.0      Bachelors         76.0        NaN    1.0
6            7              8.0      Bachelors          NaN        NaN    1.0

In [ ]:
## Converting Datatypes
df['EducationLevel'] = df['EducationLevel'].astype('category')
df['Hired'] = df['Hired'].astype('float')

In [35]:
## Saving clean file
df.to_csv("cleaned_data.csv", index=False)